baseURL = "http://vietlq.github.io/"
languageCode = "en-us"
title = "Viet's Blog"
theme = "hugo-geo"

[permalinks]
  post = "/:year/:month/:day/:title/"

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  Author = "Viet Le"
  # To satisfy hugo-geo theme
  header = "Viet's Blog"
  showglobe = true
  github = "https://github.com/vietlq"
  twitter = "https://twitter.com/vietlq"
  email = "viet@code2.pro"
  subtitle = "Food, photos and code"
  [[params.navlinks]]
    name = "About"
    url = "about"
  # To satisfy hyde theme
  description = "Food, photos and code"
  themeColor = "theme-base-08"
