baseURL = "http://vietlq.github.io/"
languageCode = "en-us"
title = "Viet's Blog"
theme = "hugo-geo"

[permalinks]
  post = "/:year/:month/:day/:title/"

[taxonomies]
  category = "categories"
  tag = "tags"

[social]
  twitter = "vietlq"

[params]
  Author = "Viet Le"
  # To satisfy hugo-geo theme
  header = "Viet's Blog"
  subtitle = "Food, photos and code"
  # Email
  email = "viet@code2.pro"
  # Twitter
  [[params.socialbuttons]]
  faicon = "twitter"
  url = "https://twitter.com/vietlq"
  # GitHub
  [[params.socialbuttons]]
  faicon = "github"
  url = "https://github.com/vietlq"
  [[params.navlinks]]
    name = "About"
    url = "about"
  # To satisfy hyde theme
  description = "Food, photos and code"
  themeColor = "theme-base-08"
