baseURL = "http://vietlq.github.io/"
languageCode = "en-us"
title = "Viet's Blog"
theme = "hugo-geo"

[permalinks]
  post = "/:year/:month/:day/:title/"

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  # To satisfy hugo-geo theme
  header = "Viet's Blog"
  Author = "Viet Le"