baseURL = "https://vietlq.github.io/"
languageCode = "en-us"
title = "Viet's Blog"
#theme = "hugo-geo"
canonifyURLs = false
theme = "hugo-theme-robust-vietlq"
googleAnalytics = "UA-1440926-3"

[permalinks]
  post = "/:year/:month/:day/:title/"

[taxonomies]
  category = "categories"
  tag = "tags"

[social]
  twitter = "vietlq"

[params]
  Author = "Viet Le"
  # To satisfy hyde theme
  description = "Food, photos and code"
  themeColor = "theme-base-08"
  # To satisfy hugo-geo theme
  header = "Viet's Blog"
  subtitle = "Food, photos and code"
  # Email
  email = "viet@code2.pro"
  # Confirm if your site is whitelisted for twitter:card
  # It's false by default to pass https://cards-dev.twitter.com/validator
  twitter_card_whitelisted = false

# Twitter
[[params.socialbuttons]]
faicon = "twitter"
url = "https://twitter.com/vietlq"

# GitHub
[[params.socialbuttons]]
faicon = "github"
url = "https://github.com/vietlq"

# GitHub
[[params.socialbuttons]]
faicon = "rss"
url = "/index.xml"

[[params.navlinks]]
name = "About"
url = "about"
