baseURL = "http://vietlq.github.io/"
languageCode = "en-us"
title = "Viet's Blog"
theme = "hyde"

[permalinks]
  post = "/:year/:month/:day/:title/"

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  Author = "Viet Le"
  # To satisfy hugo-geo theme
  header = "Viet's Blog"
  # To satisfy hyde theme
  description = "Food, photos and code"
  themeColor = "theme-base-08"
